### PR TITLE
Update validate-element-name due to security issues

### LINKED ISSUE #64: Security issues with dependency
There are some high severity issues after running npm audit.

```
❯ npm audit                                                                                                                    (master|✔)
# npm audit report

normalize-url  4.3.0 - 4.5.0 || 5.0.0 - 5.3.0 || 6.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1755
fix available via `npm audit fix`
node_modules/normalize-url

trim-newlines  <3.0.1 || =4.0.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1753
fix available via `npm audit fix --force`
Will install validate-element-name@3.0.0, which is a breaking change
node_modules/trim-newlines
  meow  3.4.0 - 5.0.0
  Depends on vulnerable versions of trim-newlines
  node_modules/meow
    validate-element-name  2.0.0 - 2.1.1
    Depends on vulnerable versions of meow
    node_modules/validate-element-name

4 high severity vulnerabilities
```

I can try to create a PR to update some dependencies.

### PR DESCRIPTION
**Pull request by fernandopasik**
Fixes #64 

I've updated `validate-element-name` to version 3 and run `npm audit fix` to update some other dependencies in package-lock.json

### CODE REVIEW

**Comment by 43081j** [comment]
sorry to be a pain, but i did some digging... this dependency is terrible, over-engineered and pulls in a fairly deep chain of dependencies for no reason.

would you mind doing a separate PR where you drop the dependency and use this package instead:

https://github.com/matthewp/is-valid-element-name

much, much better package with a lot less cruft. half of the validate-element-name code is useless, it actually duplicates checks its own dependency has already done 🤦

**Comment by fernandopasik** [comment]
No pain at all, I'll work on it

**Comment by fernandopasik** [comment]
I've looked into this. One thing that would be lost with this are all the error and warning messages. If you are ok with that I'll change the error message to just "Invalid element name." and same for the test results

**Comment by 43081j** [comment]
i think thats fine, we can just update the error message on our end to be a little more generic.

e.g. "element name is invalid and should follow the HTML standard's recommendations"

with a link to this, possibly:

https://html.spec.whatwg.org/multipage/custom-elements.html#prod-potentialcustomelementname

what do you think?

**Comment by fernandopasik** [comment]
I've done the error part. Still there's one thing we are loosing by not using `validate-element-name` which is the prefixes and double hyphens validations that happen here: https://github.com/sindresorhus/validate-element-name/blob/main/index.js#L47-L85

**Comment by 43081j** [comment]
thats ok, the invalid ones are already picked up by the potential-custom-element-name package it and the other package depend on.

the only ones we'd really be losing are the "best practice" prefixes to avoid (e.g. `x-`). we could stick that in a regex if we want rather than pull in a whole chain of packages for it

**Comment by fernandopasik** [comment]
Closing this PR in favour of #66 66

**Pull request closed without merging**
